ipetkov/crane

pkgs/default.nix

This allows for crane to work when `buildPlatform != hostPlatform`, such
as well `crossSystem` is set.
This partially addresses #4

fix(pkgs): use zstd from pkgsBuildBuild

---

checks/default.nix
docs/API.md
lib/cargoFmt.nix

* This allows potentially chaining `cargoFmt` invocations with other
derivations
Fixes #6

cargoFmt: change behavior to install cargo artifacts by default

---

CHANGELOG.md
checks/default.nix
docs/API.md
lib/cargoClippy.nix
lib/cargoTarpaulin.nix

* This allows potentially chaining invocations with other derivations more easily
Fixes #6

`cargoClippy` and `cargoTarpaulin`: change behavior to install cargo artifacts by default

---

lib/buildDepsOnly.nix
lib/mkDummySrc.nix

* Seems like Nix can get unhappy if a path fragment is evaluated too
eagerly, giving errors like
`error: access to absolute path '/Cargo.toml' is forbidden in pure eval mode (use '--impure' to override)`
* Changing to using string manipulation seems to resolve the issue
Refs #10

Form paths by concatenating a string suffix not a path

---

.github/workflows/test.yml
CHANGELOG.md
lib/findCargoFiles.nix
lib/vendorCargoRegistries.nix
lib/vendorGitDeps.nix

* `builtins.groupBy` was added in Nix 2.5
* If it's not available (i.e. evaluating with an earlier version of Nix), we will then use the `lib.groupBy` implementation instead
Fixes #15

Add compatibility fallback for builtins.groupBy 

---

CHANGELOG.md
docs/API.md
lib/buildDepsOnly.nix
lib/cargoClippy.nix

This allows caching all artifacts (including from dev-dependencies) such
that tools like clippy don't have to generate them every time they run.

buildDepsOnly: add `--all-targets` to default cargoCheckCommand

---

checks/cleanCargoTomlTests/default.nix
checks/mkDummySrcTests/default.nix
lib/crateNameFromCargoToml.nix
lib/vendorCargoDeps.nix

when trying to use crane with a non local src (eg, not `./.`) we get the error
```
$ nix flake show
<...>
error: access to absolute path '/Cargo.toml' is forbidden in pure eval mode (use '--impure' to override)
(use '--show-trace' to show detailed location information)
```
To fix this, we quote the relative paths so to properly append them to the base path.
https://nixos.wiki/wiki/Nix_Expression_Language#Coercing_a_relative_path_with_interpolated_variables_to_an_absolute_path_.28for_imports.29
```nix
{
description = "Build a cargo project without extra checks";
inputs = {
nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
crane = {
url = "github:ipetkov/crane";
inputs.nixpkgs.follows = "nixpkgs";
};
external-crate-source = {
url = "github:ray-kast/empress";
flake = false;
}; …
```

fix(nix-relative-paths): quote relative paths to allow for external sources

---

examples/quick-start/flake.nix

* Seems like cargo-tarpaulin only officially supports x86_64 systems,
and more recent versions are marked as broken on other systems in
nixpkgs
Fixes #33

quick-start: update to conditionally enable cargo-tarpaulin

---

.github/workflows/test.yml
CHANGELOG.md
README.md
checks/default.nix
examples/alt-registry/flake.nix
examples/custom-toolchain/flake.nix
examples/quick-start-simple/flake.nix
examples/quick-start/flake.nix
flake.lock
flake.nix
lib/findCargoFiles.nix
lib/vendorCargoRegistries.nix
lib/vendorGitDeps.nix

This drops compatibility for Nix versions below 2.8.1

ci: bump stable Nix to use 22.05 release

---

CHANGELOG.md
checks/cleanCargoTomlTests/complex/expected.toml
checks/default.nix
checks/mkDummySrcTests/single/expected/Cargo.toml
checks/mkDummySrcTests/workspace/expected/member/foo/bar/baz/Cargo.toml
checks/mkDummySrcTests/workspace/expected/member/qux/Cargo.toml
default.nix
docs/API.md
flake.lock
flake.nix
lib/cleanCargoToml.nix
lib/crateNameFromCargoToml.nix
lib/default.nix
lib/vendorCargoDeps.nix
lib/vendorCargoRegistries.nix
lib/vendorGitDeps.nix
lib/writeTOML.nix
shell.nix

I'd like to use Crane but I have no interest in starting to use Flakes.
With this change it's possible to use Crane without flakes like:
``` nix
{ lib ? pkgs.lib
, pkgs ? import <nixpkgs> { }
}:
let
craneLib = import ../crane { inherit pkgs; };
src = lib.cleanSource ./.;
cargoArtifacts = craneLib.buildDepsOnly {
inherit src;
};
in craneLib.buildPackage {
inherit cargoArtifacts src;
}
```

Make crane possible to use without flakes

---

lib/buildDepsOnly.nix

* Previously we would manually copy over any Cargo.lock file from the
source to the dummified source
* Now, `mkDummySrc` will implicitly copy the file if it is present, or
ignore it if missing, so this check is a bit overzealous now
* Loosening this check also allows callers to sneak in their own
Cargo.lock file (e.g. through a patch phase) while still avoiding IFD
Related to #18 #32

buildDepsOnly: remove (now unnecessary) cargoLock check

---

lib/mkDummySrc.nix

This removes an IFD if the cargo lock path is the output of a derivation. The check for this is useless IMO, as the build will fail anyways if the specified path doesn't exist. This change allows dream2nix to use crane without triggering any IFD (when building crates that are local / flake sources).

fix(mkDummySrc): don't check if cargo lock path exists

---

lib/vendorCargoRegistries.nix
lib/vendorGitDeps.nix

* lib.groupBy will default to builtins.groupBy if available, so it is
safer to use
Fixes #41

Import groupBy from lib not builtins

---

.github/workflows/test.yml
CHANGELOG.md
README.md
docs/API.md
examples/cross-musl/flake.nix
examples/cross-rust-overlay/flake.nix
examples/custom-toolchain/flake.nix
lib/default.nix

This should make it simpler to use a custom rust toolchain without having to remember to override each specific tool.
Fixes #43

Add .overrideToolchain convenience method

---

CHANGELOG.md
checks/mkDummySrcTests/default.nix
lib/mkDummySrc.nix

mkDummySrc: fix handling when src is already filtered

---

CHANGELOG.md
checks/compilesFresh.nix
docs/API.md
lib/buildDepsOnly.nix
lib/buildPackage.nix
lib/cargoBuild.nix
lib/cargoClippy.nix
lib/cargoTarpaulin.nix
lib/mkCargoDerivation.nix
lib/vendorGitDeps.nix
pkgs/cargoHelperFunctions.sh
pkgs/cargoHelperFunctionsHook.nix
pkgs/configureCargoCommonVarsHook.sh
pkgs/default.nix

* The `--workspace` flag is no longer set for cargo invocations by default. Please set `cargoExtraArgs = "--workspace";` to bring this behavior back
* The `$CARGO_PROFILE` environment variable can be used to specify exactly which cargo profile is used for the invocation. By default the `release` profile will be used. Set `CARGO_PROFILE = "something else";` in the derivation to change it, or set it to `null` to omit specifying a profile altogether
* All cargo invocations are now automatically logged

Update default flags passed to cargo

---

CHANGELOG.md
checks/default.nix
docs/API.md
pkgs/configureCargoCommonVarsHook.sh

Fixes a few issues with using `CARGO_PROFILE`
* Correct the docs that the environment variable needs to be set to an empty string (not null) to actually be disabled
- Nix appears to skip setting null environment variables which makes it look like the variable wasn't set to begin with
* Also correct the behavior of setting `CARGO_PROFILE` by default, specifically only set the default value if the variable is unset (but if it is set and empty, leave it as is)

Correct docs on disabling CARGO_PROFILE from being used

---

CHANGELOG.md
checks/default.nix
docs/API.md
examples/quick-start/flake.nix
flake.lock
lib/cargoAudit.nix
lib/default.nix

This adds support for cargo-audit as a possible check when using crane. Cargo-audit uses a local clone of a repository of security advisories- this must be provided, but doing so means that crane doesn't need to be updated with repository updates.
Example usage:
```
{
inputs = {
...
crane = {
url = "github:ipetkov/crane";
inputs.nixpkgs.follows = "nixpkgs";
};
advisory-db = {
url = "github:rustsec/advisory-db";
flake = false;
};
...
};  
outputs = {
self,
nixpkgs,
crane,
advisory-db,
...
}:
flake-utils.lib.eachDefaultSystem (system: let
pkgs = import nixpkgs {inherit system overlays;};
craneLib = (crane.mkLib pkgs).overrideToolchain rust;
src = ./.;
...
in rec {
...
checks =
{
app-fmt = craneLib.cargoFmt {
inherit src;
};
app-audit = craneLib.cargoAudit {
inherit src;
inherit advisory-db; …
```

Add support for cargo audit

---

checks/cargoAudit.nix
checks/default.nix
docs/API.md
lib/cargoAudit.nix

Seems like cargo-audit only needs a `Cargo.lock` file and an advisory
database to run, so we can filter the inputs down even further to
avoid rebuilds and file copying into the Nix sandbox
cc @ngerstle-cognite

cargoAudit: filter source to only include Cargo.lock files

---

CHANGELOG.md
lib/vendorGitDeps.nix

If the `Cargo.lock` file is missing a locked revision for a git dependency we should throw a descriptive error (with a suggestion for resolving it) instead of failing with a weird error.
Fixes #57 
* Can't add a good test for this, nix has `builtins.tryEval` but you cannot access the error itself so probably wouldn't be a good test
* Not relevant
* Not relevant

vendorGitDeps: throw descriptive error if locked revision is missing

---

CHANGELOG.md
README.md
checks/clippy/default.nix
docs/API.md
examples/quick-start/flake.nix
lib/cargoClippy.nix

This allows callers to opt-out of using `--all-targets` without having to override the entire cargo command itself
Fixes #64

cargoClippy: add --all-targets to default cargoClippyExtraArgs

---

docs/API.md

Tweak `cargoBuild` docs to mention `doInstallCargoArtifacts` to be hopefully less confusing about when cargo artifacts are installed.
Fixes #74

docs: tweak `cargoBuild` docs to mention `doInstallCargoArtifacts`

---

CHANGELOG.md
checks/default.nix
docs/API.md
lib/mkCargoDerivation.nix

Allow ergonomically overriding stdenv without having to override it for the entire library's scope
Refs #99

mkCargoDerivation: allow ergonomically overriding stdenv

---

CHANGELOG.md
checks/default.nix
docs/API.md
lib/buildPackage.nix
lib/mkCargoDerivation.nix

This is done to avoid breaking builds by including puts happen to have setup-hooks which try to claim the configure phase (such as `cmake`).
The old behavior can be brought back by setting `configurePhase = null;` on the derivation.
Fixes #104

mkCargoDerivation: add default `configurePhase`

---

CHANGELOG.md
checks/compilesFresh.nix
checks/default.nix
checks/features/default.nix
docs/API.md
examples/quick-start/flake.nix
lib/cargoDoc.nix
lib/default.nix

cargoDoc: add ability to run `cargo doc` on a workspace
Fixes #89

cargoDoc: add ability to run `cargo doc` on a workspace

---

CHANGELOG.md
README.md
checks/default.nix
docs/API.md
examples/alt-registry/flake.nix
examples/cross-musl/flake.nix
examples/cross-rust-overlay/flake.nix
examples/custom-toolchain/flake.nix
examples/quick-start-simple/flake.nix
examples/quick-start/flake.nix
lib/cleanCargoSource.nix
lib/default.nix
lib/filterCargoSources.nix

Add `cleanCargoSource` and `filterCargoSources` for easy source filtering. Examples have also been updated to highlight using `cleanCargoSource`, though it is not required.
Fixes #79

Add cleanCargoSource and filterCargoSources

---

CHANGELOG.md
docs/API.md
lib/buildPackage.nix
lib/mkCargoDerivation.nix
pkgs/inheritCargoArtifacts.nix
pkgs/inheritCargoArtifactsHook.sh
pkgs/installCargoArtifacts.nix
pkgs/installCargoArtifactsHook.sh
pkgs/installFromCargoBuildLog.nix
pkgs/installFromCargoBuildLogHook.sh
pkgs/removeReferencesToVendoredSources.nix

* Using substitutions for build hooks is a great way to ensure the necessary utility is present without making the caller supply it to the builder, except it makes things confusing when applying overrides
* For example, the `installFromCargoBuildLog` hook was inadvertently ignoring any `cargo` overrides applied to the entire `lib` instantiation
* By removing all explicit substations we also side step the issue of trying to select the correct build/host/target version of the tool and use whatever is present in the build environment
Fixes #125

hooks: do not use substitutions for needed tools

---

CHANGELOG.md
docs/API.md
lib/cargoAudit.nix
lib/cargoClippy.nix
lib/cargoDoc.nix
lib/cargoFmt.nix
lib/cargoNextest.nix
lib/cargoTarpaulin.nix
lib/mkCargoDerivation.nix

`cargoBuild` originally started out the central place for preparing a derivation for running cargo (e.g. vendoring dependencies, building only dependnecies, setting the derivation's `pname` and `version`) and was meant to be a foundation for defining additional commands (e.g. running `clippy`, or `cargo audit`, etc.).
In reality it [ended up doing a bit too much and causing friction for customization](https://github.com/ipetkov/crane/issues/89#issuecomment-1229261734). Keeping up with the pattern of having a `cargoFoo` command (which only runs the "foo" procedure) `cargoBuild` should only build (and not run tests).
In preparation for changing the behavior of `cargoBuild` (to come in a future change), all internal usage of `cargoBuild` has been replaced with using `mkCargoDerivation` …

Refactor internal usage of `cargoBuild`

---

CHANGELOG.md
checks/default.nix
docs/API.md
flake.nix
lib/cargoTarpaulin.nix
pkgs/default.nix

Cleanup deprecated bindings to the `packages` flake output

Cleanup deprecated bindings

---

CHANGELOG.md
checks/default.nix
docs/API.md
lib/buildDepsOnly.nix
lib/buildPackage.nix
lib/cargoBuild.nix

Make `cargoBuild` focused on doing just one thing: building a workspace. Namely, _not_ running tests since we have `cargoTest` now.
`buildPackage` will continue to run tests if `doCheck = true;` is set
Fixes #134

Refactor `cargoBuild` so it only builds

---

CHANGELOG.md
docs/API.md
lib/crateNameFromCargoToml.nix

`crateNameFromCargoToml` now takes workspace inheritance into account. If a crate does not specify `package.version` in its (root) Cargo.toml but does specify `workspace.package.version` then the latter will be returned.
Refs #113 
Fixes #143

crateNameFromCargoToml: handle workspace inheritance

---

CHANGELOG.md
ci/run-tests.sh
docs/API.md
lib/buildPackage.nix
lib/setupHooks/inheritCargoArtifactsHook.sh
lib/setupHooks/installCargoArtifactsHook.sh

* Define a new installation mode which symlinks identical artifacts
against a directory of previously generated ones
* This allows for linear space usage in the Nix store across many
chained derivations (as opposed to using a zstd compressed tarball
which uses quadratic space across many chained derivations)
* This new installation mode is the new default for all cargo based
builds. The previous behavior is still available by setting
`installCargoArtifactsMode = "use-zstd";` on a derivation
* `buildPackage` will continue to use zstd compressed tarballs while
building dependencies (unless either of `cargoArtifacts` or
`installCargoArtifactsMode` is defined, in which case they will be
honored)
Fixes #76

Change default cargo artifact installation to use symlinks where possible

---

CHANGELOG.md
lib/registryFromGitIndex.nix

Registry repos can get quite large if they have a lot of publish traffic. `registryFromGitIndex` only needs to check out a particular commit and observe the `config.json` file, and since the history is not significant we can use a shallow clone to speed things up

registryFromGitIndex: use shallow git checkouts

---

.github/workflows/test.yml
CHANGELOG.md
checks/default.nix
checks/nextest.nix

The 22.11 branch was released and 22.05 is now deprecated

ci: test against 22.11 and stop testing 22.05

---

CHANGELOG.md
lib/setupHooks/installCargoArtifactsHook.sh

zstd compression is supposed to be deterministic (even with multiple threads) so we might as well allow it to use as many cores as are available to the derivation
Fixes #182

zstd: use as many threads as we can when compressing

---

examples/quick-start/flake.nix

Upon further testing it looks like the crate-doc quick start also needs buildInputs when you add more involved doc tests on macos. Other platforms should remain unaffected.

Add buildInputs to quick-start doc

---

lib/mkDummySrc.nix

* When checking the original source for its name, make sure we throw away the string context so we don't end up actually depending on the original source instead of the cleaned one
Fixes https://github.com/ipetkov/crane/issues/194

mkDummySource: fix build invalidation regression

---

.github/workflows/test.yml

* By default the GITHUB_TOKEN is set as an access token (to avoid rate limiting) so we don't have to do it explicitly

ci: bump to cachix/install-nix-action@19

---

CHANGELOG.md
checks/default.nix
lib/setupHooks/installFromCargoBuildLogHook.sh

Fix issues with non-JSON values in `cargoBuildLog` by ignoring non-json lines.
In some cases using cargo with `message-format=json` prints some non-json lines: https://github.com/rust-lang/cargo/issues/8179
When that's the case crane currently fails with:
```
searching for bins/libs to install from cargo build log at cargoBuildLogGbmv.json
parse error: Invalid numeric literal at line 390, column 6
```

ignore non-json lines in cargoBuildLog

---

CHANGELOG.md
checks/default.nix
docs/API.md
lib/crateNameFromCargoToml.nix
lib/mkCargoDerivation.nix

Emit a warning whenever `crateNameFromCargoToml` fails to find an appropriate value for a package's `name` or `version` fields. This should make it a bit more obvious when this happens (i.e. so the caller can explicitly set an appropriate value and not have things like `nix run` break "inexplicably") but still allow the build to go through.
Fixes https://github.com/ipetkov/crane/issues/236

crateNameFromCargoToml: warn when values can't be found

---

CHANGELOG.md
lib/buildDepsOnly.nix

Warn if both `src` and `dummySrc` are set to hopefully avoid debugging confusion as reported in https://github.com/ipetkov/crane/issues/241
Fixes https://github.com/ipetkov/crane/issues/241

buildDepsOnly: warn if both `src` and `dummySrc` are set

---

CHANGELOG.md
lib/mkDummySrc.nix

Turns out that for whatever reason a flake source like `src = ./.;` might show up in the Nix store with _two_ hashes instead of one (not sure if this is a regression somewhere upstream, but even if it is, let's not trip up on it)
Fixes https://github.com/ipetkov/crane/issues/242

mkDummySrc: avoid invalidation if the source name has two hashes

---

CHANGELOG.md
checks/default.nix
docs/API.md
lib/mkCargoDerivation.nix
lib/vendorCargoDeps.nix

So I can process `Cargo.lock` with nix without using IFD: https://github.com/nix-community/nix-init/commit/27ed3100259b980633caccc1ac8a7dd6440ba3dd

feat: add `cargoLockParsed` option

---

CHANGELOG.md
docs/API.md

* `lib` is already a common import representing `pkgs.lib`
* Consistently using `craneLib` in the docs and examples will ensure better clarity

docs: replace references to `lib` with `craneLib`

---

CHANGELOG.md
docs/API.md
lib/buildPackage.nix

* When setting a default value for `cargoArtifacts`,
`buildPackage` will now ignore `installPhase` and `installPhaseCommand` when
calling `buildPackage`. To bring back the old behavior, please specify
`cargoArtifacts` explicitly
Refs https://github.com/ipetkov/crane/discussions/296

buildPackage: don't inherit installPhase when calling buildDepsOnly

---

checks/trunk.nix
checks/trunk/index.html
checks/trunk/main.scss
examples/trunk-workspace/client/index.html
examples/trunk-workspace/client/main.scss
examples/trunk/index.html
examples/trunk/main.scss
lib/buildTrunkPackage.nix

The current format for `TRUNK_TOOLS_SASS` is incorrect from Trunk's perspective, it expects the entire first line from the command `sass --version`, this is no problem with the native version of `dart-sass` which outputs only the version `1.56.0`. But the version currently in use is compiled to javascript and has aditional information `1.56.0 compiled with dart2js 2.18.4`.
This PR fixes the proccessing done to `TRUNK_TOOLS_SASS` to match what is expected from Trunk. It also tests sass compilation, and adds a small sass file to the trunk examples.
Thanks to this comment for highligthing the issue: https://github.com/ipetkov/crane/issues/295#issuecomment-1532096291.

fix: building trunk projects that use sass, add test

---

checks/trunk.nix
examples/trunk-workspace/flake.nix
examples/trunk/flake.nix

There are currently two issues that cause unnecessary recompilation in the `trunk-workspace` example:
- Excluding the client from native artifacts causes it to be built when running clippy.
- `CARGO_BUILD_TARGET` is not set in `wasmArgs`, that was previously done automatically.
Also replaced all usage `cargoExtraArgs = "--target..."` with `CARGO_BUILD_TARGET`, so it's easier to add arguments without overwriting the target.

fix: incremental compilation in trunk examples, set target using env var

---

examples/cross-rust-overlay/flake.nix

Seems like these SDKs aren't necessary, and worse, they're causing issues for some reason. Might as well simplify the example a bit!
Fixes #320

examples: remove darwin SDKs from cross compile example

---

checks/simple-git/Cargo.lock
checks/simple-git/Cargo.toml

Looks like the `libc` crate changed their default branch from `master` to `main` and when the repo fell out of the cache it broke CI...

checks: Update libc branch

---

CHANGELOG.md
checks/cleanCargoTomlTests/complex/expected.toml
lib/cleanCargoToml.nix

For projects using version != 2021 and resolver = 2, the resolver information needs to be kept or otherwise the dependency build might fail. It doesn't hurt to always keep the information, so it's now always included in the cleaned Cargo.toml.
I created a minimal repro of the issue [here](https://github.com/Detegr/crane-resolver-repro).

Keep "resolver" when cleaning Cargo.toml

---

CHANGELOG.md
lib/buildTrunkPackage.nix

The output of `buildTrunkPackage` should never have runtime dependencies. 
Not only are they redundant but they also increase the closure greatly.
This makes a big difference when using nix to build docker images (from 64Mb to 5Mb).

fix: Strip store references in buildTrunkPackage

---

CHANGELOG.md
lib/buildTrunkPackage.nix

Trunk expect a version number with this specific format: "version_{num}"
(see https://github.com/thedodd/trunk/blob/master/src/tools.rs#L92)
When using `<link data-trunk rel="rust" data-wasm-opt="4" />` `buildTrunkPackage` fails while trying to download `wasm-opt`
For the test part, we can add the `data-wasm-opt="4"` to one of the existing test, but I'm waiting your input before doing so.

fix(Trunk): Set the `wasm-opt` version as expected by Trunk

---

CHANGELOG.md
docs/API.md
lib/buildPackage.nix

Currently, install hooks get passed down to `buildDepsOnly` call, and, if they need any source files not included in the dummy source, build fails.
It seems reasonable to clean them together with custom install commands.

Clean install hooks from buildDepsOnly invocation

---

CHANGELOG.md
checks/default.nix
docs/API.md
examples/alt-registry/.cargo/config.toml
examples/alt-registry/Cargo.lock
examples/alt-registry/Cargo.toml
examples/alt-registry/flake.nix
flake.lock
lib/default.nix
lib/registryFromDownloadUrl.nix
lib/registryFromSparse.nix
lib/urlForCargoPackage.nix
lib/vendorCargoRegistries.nix

With Cargo 1.68.0, sparse registries were made stable. With sparse registries, index metadata is stored in an HTTP api rather than in a git repository.
As relevant to Crane, the relevant changes are mostly that registries do not always start with `registry+` and mostly start with `registry+` or `sparse+` depending on whether the registry is sparse or not.
This PR adjusts the core of Crane to differentiate between `registry` and `sparse`, and adds a new sparse registry factory to make things easy.
I'm new to Nix, so it's possible and likely that my code is incorrect.

Natively support sparse registries

---

.github/workflows/pages.yml
.github/workflows/test.yml
.github/workflows/update-flake.yml
examples/alt-registry/.cargo/config.toml
examples/alt-registry/Cargo.lock
examples/alt-registry/Cargo.toml
examples/alt-registry/flake.nix
flake.nix

* crates.io uses the sparse registry by default, and trying to
explicitly register a sparse registry for it results in errors

Fix alt-registry example

---

CHANGELOG.md
docs/API.md
lib/cargoTarpaulin.nix
lib/mkCargoDerivation.nix
lib/setupHooks/inheritCargoArtifacts.nix
lib/setupHooks/inheritCargoArtifactsHook.sh

This is a much simpler (i.e. less ambitious, and easier to land) version of #322 
Dependency `*.rlib` and `*.rmeta` files never change (as they would only change if `Cargo.lock` changes which would invalidate the entire build anyway) so we can get away with symlinking them to the inherited artifacts instead of having to deeply copy the files.
Fewer copies means faster builds!

inheritCargoArtifactsHook: symlink dependency rlib and rmeta files

---

CHANGELOG.md
docs/API.md
lib/cargoTarpaulin.nix
lib/setupHooks/inheritCargoArtifactsHook.sh

Allow disabling the symlinking behavior of `inheritCargoArtifactsHook` in case it becomes necessary

inheritCargoArtifactsHook: allow disabling symlink behavior

---

CHANGELOG.md
pkgs/crane-utils/Cargo.lock

Couldn’t use `crane` due to `crane-utils` with uses `proc-macro2` transitively (I think this is from `serde-derive`) fails to build with Rust nightly 2023-06-28
I’m probably having an overlay for the latest nighly on Rust, where this feature gate is removed (somehow)
```bash
error: builder for '/nix/store/dcd0wxdg3r5z1salc20k1q8k1swmkwhj-crane-utils-deps-0.1.0.drv' failed with exit code 101;
last 10 log lines:
>    Compiling indexmap v1.9.3
>     Checking pretty_assertions v1.3.0
> error[E0635]: unknown feature `proc_macro_span_shrink`
>   --> /nix/store/ijgx3vbi3i4jd376c91jymf7pih68zd9-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d
0/proc-macro2-1.0.56/src/lib.rs:92:30
>    |
> 92 |     feature(proc_macro_span, proc_macro_span_shrink)
>    | …
```

deps: update cargo-utils dependencies, should fix builds from nightly rust

---

CHANGELOG.md
checks/default.nix
lib/setupHooks/inheritCargoArtifactsHook.sh

* This ensures that when doNotLinkInheritedArtifacts is set, artifact symlinks are deeply resolved
Fixes #356

inheritCargoArtifactsHook: fix doNotLinkInheritedArtifacts handling

---

CHANGELOG.md
docs/API.md
lib/buildTrunkPackage.nix

Replace the javascript version of `dart-sass` with a native binary version. `nodePackages.sass` and `dart-sass` are the same program compiled to different targets, so this is not a breaking change, except maybe bumping the minimum supported version of nixpkgs to 23.05. 
Should improve build times and reduce disk usage by not requiring nodejs.

Trunk: use native dart-sass

---

CHANGELOG.md
checks/default.nix
docs/API.md
lib/buildDepsOnly.nix
lib/buildPackage.nix
lib/cargoBuild.nix
lib/cargoClippy.nix
lib/cargoDoc.nix
lib/cargoLlvmCov.nix
lib/cargoTest.nix

The new defaults should help catch situations where a `Cargo.lock` file isn't fully up to date and leading to cache invalidations.
Fixes https://github.com/ipetkov/crane/issues/372

various: change `cargoExtraArgs` defaults to include `--locked`

---

CHANGELOG.md
docs/API.md
lib/cargoDoc.nix

Do not install cargo artifacts by default
Refs https://github.com/ipetkov/crane/pull/379

cargoDoc: do not install cargo artifacts by default

---

CHANGELOG.md
checks/cargoAudit.nix
lib/downloadCargoPackage.nix
lib/downloadCargoPackageFromGit.nix
lib/mkDummySrc.nix

Switch to using runCommand to improve caching
For example, commands which extract a tarball should be cached (i.e should use `runCommand` not `runCommandLocal`) because it allows builds to download the unpacked result instead of having to write both to the store

various: switch to using runCommand to improve caching

---

.github/workflows/update-flake.yml

Auto-approve flake update PRs as long as the test suite is passing. Also update the flake every 2 weeks instead of 4

Auto-approve flake update PRs

---

flake.nix

Crane is one of the most popular libraries on FlakeHub, but it won't appear as "featured" on the homepage because there is no description. I thought I'd help fix that if you want it!

flake: add a description

---

CHANGELOG.md
lib/buildPackage.nix

* When https://github.com/ipetkov/crane/pull/334 fixed ignoring caller-specified installation hooks, it inadvertently turned off the build hook which installed the actual cargo artifacts

buildPackage: fix issue with inheriting default depsOnly artifacts

---

docs/API.md
lib/cargoTarpaulin.nix

fixes #404 
verified it in one of my projects using the `cargoTarpaulin` derivation

fix #404 - lib/cargoTarpaulin: lowercase --out xml argument

---

CHANGELOG.md
pkgs/crane-utils/Cargo.lock
pkgs/crane-utils/Cargo.toml
pkgs/crane-utils/src/bin/crane-resolve-workspace-inheritance.rs

As discussed in #394, crane currently uses the [`toml` crate] dependency in `crane-resolve-workspace-inheritance.rs` in order to merge the workspace root Cargo.toml with the current crate's Cargo.toml. This script is run on all git dependencies of the built crate.
One unfortunate side effect of using the [`toml` crate] is that all comments are removed from Cargo.toml.  This is an issue if proc macros or build scripts are expecting to read non-TOML metadata from Cargo.toml (e.g. [`document-features`] used by some embedded libraries, such as [`embassy-stmf32`](https://github.com/embassy-rs/embassy/tree/main/embassy-stm32))
This PR adapts the existing `crane-resolve-workspace-inheritance.rs` script to use [`toml_edit`] instead of the [`toml` crate], to preserve comments.
- There are two …

Replace `toml` dependency with `toml_edit` to preserve comments

---

CHANGELOG.md
checks/simple-with-audit-toml/.cargo/audit.toml
docs/API.md
lib/cargoAudit.nix

* Checking for yanked crates requires network access (to ping the crates.io index) which won't work from inside the sandbox
Fixes https://github.com/ipetkov/crane/issues/421

cargoAudit: ignore yanked crates by default

---

CHANGELOG.md
checks/default.nix
docs/API.md
lib/default.nix
lib/mkCargoDerivation.nix
lib/setupHooks/replaceCargoLockHook.nix
lib/setupHooks/replaceCargoLockHook.sh

* The vendoring helpers already accept a `cargoLock` override, so automatically linking it in the derivation (if set) makes it a bit easier without having the caller manually do the link themselves
Fixes https://github.com/ipetkov/crane/issues/422

mkCargoDerivation: replace Cargo.lock with contents of `cargoLock`

---

.github/workflows/test.yml

* PRs are more ephemeral and if they cause massive rebuilds, they're likely to continue causing rebuilds as feedback is being addressed, so we can cut down on the cache (push) pressure until the changes are actually landed

ci: only push to cachix on the main branch

---

checks/default.nix
docs/introduction/artifact-reuse.md
docs/introduction/sequential-builds.md
examples/alt-registry/flake.nix
examples/build-std/flake.nix
examples/cross-musl/flake.nix
examples/cross-rust-overlay/flake.nix
examples/custom-toolchain/flake.nix
examples/quick-start-simple/flake.nix
examples/quick-start/flake.nix
examples/trunk-workspace/flake.nix
examples/trunk/flake.nix

It can be a common source of rebuilds if `buildInputs`/`nativeBuildInputs` are not set up properly, plus it's good hygiene to always have it on.
There are no plans to make this a default behavior of `mkCargoDerivation`, however, as that would be a departure from `mkDerivation` which might end up being surprising
Fixes https://github.com/ipetkov/crane/issues/403

chore: update all examples with `strictDeps = true;`

---

.github/workflows/test.yml
ci/fast-flake-check.sh
examples/cross-windows/flake.nix

We can use `nix flake check --no-build` to evaluate the rest of the flake, but still do a fast build of the checks themselves

ci: also use fast-flake-check for examples

---

CHANGELOG.md
checks/default.nix
docs/API.md
lib/setupHooks/replaceCargoLockHook.sh

Copying the overridden Cargo.lock cannot be done as a `postUnpack` hook because the builder does not `cd` into the unpacked source until after those hooks are done (thus we effectively end up linking the `Cargo.lock` to `..` when the build runs).
The fix is to change the hook to run later as a `prePatch` hook
Fixes https://github.com/ipetkov/crane/issues/422

replaceCargoLockHook: run as prePatchHook not postUnpack

---

.github/workflows/test.yml
ci/check-example.sh
ci/fast-flake-check.sh
ci/ref-from-lock.sh
test/flake.lock
test/flake.nix

Should give us better/more consistent caching (and avoid random headaches when the nixpkgs-darwin branch updates and then we're stuck recompiling for hours for an unrelated change)

ci: pin all example inputs with a single testing flake.lock

---

CHANGELOG.md
extra-tests/dummy-does-not-depend-on-flake-source-via-path/flake.nix
extra-tests/dummy-does-not-depend-on-flake-source-via-self/flake.nix
extra-tests/fetch-cargo-git/flake.nix
flake.lock
flake.nix
shell.nix

There's no point in polluting downstreams' lockfiles with our own internal dependencies, we can hide them by using an internal `flake.lock`

chore: drop all public dependencies except for `nixpkgs`

---

CHANGELOG.md
docs/API.md
lib/buildPackage.nix
lib/buildTrunkPackage.nix
lib/setupHooks/installCargoArtifactsHook.sh

Now that we have incremental zstd compression we can change the default artifact installation mode to `"use-zstd"`. To get the old behavior back set `installCargoArtifactsMode = "use-symlink";`
Fixes https://github.com/ipetkov/crane/issues/441

installCargoArtifactsHook: change default installation mode to use-zstd

---

.gitignore
CHANGELOG.md
extra-tests/alt-store/flake.nix
extra-tests/alt-store/test.sh
extra-tests/test.sh
lib/mkDummySrc.nix

* Turns out if a build is invoked with `--store` then the source cleaning filter will observe paths rooted at the alternative store which breaks out previous string handling (and results in incorrectly ignoring files which should be included)
Fixes https://github.com/ipetkov/crane/issues/446

mkDummySrc: fix cleaning to work with Nix store overrides

---

checks/default.nix
docs/API.md

* Looks like Nix 2.19.0 doesn't like it when a path starts with `.` so this updates the examples and tests to avoid doing that

fix: avoid path starts with illegal character error

---

CHANGELOG.md
lib/buildTrunkPackage.nix

Hello again! Updating my older rust project that uses `trunk` was seamless using crane's `buildTrunkPackage`.
The build Just Worked :tm: without any issues :slightly_smiling_face:
While attempting to reuse the `preConfigure` hook in  buildTrunkPackage.nix (to build a trunk wrapper script for use in devshells) the `shellcheck` run by `writeShellApplication` gave some warnings:
<details>
<summary>Snippet of nix source</summary>
```nix
{
frontend = craneLib.buildTrunkPackage { ...omitted... };
trunkOffline = pkgs.writeShellApplication {
name = "trunk-offline";
text = ''
${frontend.preConfigure}
${pkgs.trunk}/bin/trunk "$@"
'';
};
}
```
</details>
Shellcheck warnings:
```text
In /nix/store/w6lkjm5zds14lbyj6sn2051kvp789l6k-trunk-offline/bin/trunk-offline line 7:
export TRUNK_TOOLS_SASS=$(sass …
```

buildTrunkPackage - separately export and declare shell variables (SC2155)

---

examples/alt-registry/flake.nix
examples/cross-windows/flake.nix
examples/end-to-end-testing/flake.nix
examples/quick-start-simple/flake.nix
examples/quick-start/flake.nix
flake.nix

* i.e. if we neither set localSystem/crossSystem, nor add overlays, we can directly utilize `nixpkgs.legacyPackages.${system}` directly and avoid re-evaluating nixpkgs an additional time

examples: avoid re-instantiating nixpkgs where possible

---

CHANGELOG.md
docs/API.md
lib/buildDepsOnly.nix

Fixes https://github.com/ipetkov/crane/issues/468

buildDepsOnly: pass --no-run to cargo test by default

---

CHANGELOG.md
pkgs/crane-utils/src/bin/crane-resolve-workspace-inheritance.rs

Closes https://github.com/ipetkov/crane/issues/480 - there could probably be a nicer way to handle this, but I went with the simplest approach I could come up with - note that it appears that `lints.workspace = true` does not support per-crate overrides of the workspace setting at this time, so we don't actually need to merge anything within the crates themselves.

feat: support workspace `lints`

---

CHANGELOG.md
checks/default.nix
flake.nix
lib/default.nix
lib/downloadCargoPackage.nix
lib/downloadCargoPackageFromGit.nix
lib/mkDummySrc.nix
lib/vendorCargoRegistries.nix
lib/vendorGitDeps.nix
lib/vendorMultipleCargoDeps.nix
lib/writeTOML.nix
pkgs/crane-utils/default.nix

* Source vendoring is passed as a standalone attribute to `mkCargoDerivation`, meaning it does not automagically get spliced with the correct local/cross system inputs (i.e. what would happen if it was a `depsBuildBuild` entry)
* To fix this we need to make sure that `vendorCargoDeps` and all of its transitive dependencies always use `runCommand` (and friends) from their `pkgsBuildBuild` equivalent. This should always be safe to do (even for cross-builds) since this amounts to building up a bunch of sources which will be read by the build system
* Unfortunately I had to manually specify `pkgsBuildBuild.whatever` in multiple places as I could not get things to work by messing with the `callPackage` definition. Perhaps we should be using `makeScopeWithSplicing'` instead of `makeScope` when …

vendorCargoDeps: manually splice packages to avoid cross build issues

---

CHANGELOG.md
checks/cleanCargoTomlTests/complex/Cargo.toml
checks/default.nix
checks/workspace/Cargo.lock
checks/workspace/Cargo.toml
checks/workspace/hello/Cargo.toml
lib/cleanCargoToml.nix

The `[lints]` and `[workspace.lints]` tables only affect compiling crates in the current workspace, but don't affect any dependency crates (since cargo will pass in `--cap-lints allow` when building those). Thus, when we're dummifying sources, stripping these out gives us two main benefits:
* Changing (only) the lints table will now avoid rebuilding dependencies since stripping the values means we don't invalidate build caches
* Avoids build errors if the dummified sources happen to emit or allow a lint which was marked as `deny` or `forbid` by the project itself

cleanCargoToml: strip out `[lints]` definitions when cleaning

---

checks/trunk.nix
docs/API.md
docs/advanced/overriding-function-behavior.md
docs/faq/custom-nixpkgs.md
docs/faq/invalid-metadata-files-for-crate.md
examples/trunk-workspace/flake.nix
examples/trunk/flake.nix
flake.nix
lib/default.nix

It used to be that `makeScope`'s `overrideScope` was deprecated in favor of `overrideScope'`. With nixpkgs-23.11 `overrideScope`'s signature was changed to that of `overrideScope'` and so the latter is now deprecated (and going away in the next stable release).
This changes all internal usage and docs to use `overrideScope` ahead of the deprecation

chore: replace overrideScope' with overrideScope

---

docs/SUMMARY.md
docs/faq/rebuilds-bindgen.md
docs/faq/sandbox-unfriendly-build-scripts.md

Document workaround for the `bindgen` crate being rebuilt.
Originally reported in https://github.com/ipetkov/crane/discussions/518#discussion-6194531

docs: document workaround for the `bindgen` crate being rebuilt

---

CHANGELOG.md
lib/vendorMultipleCargoDeps.nix

The docs state that you can use `registries` in `vendorMultipleCargoDeps`. The code does support that. However, it was missed that you need to either allow `registries` directly as a keyword in the function parameters or you need to add a `, ...`. I don't know which version you would prefer, so I simply went with the more strict version for now. Let me know what changes I need to include or feel free to commit to my branch.

fix: allow registries in vendorMultipleCargoDeps as documented

---

lib/vendorMultipleCargoDeps.nix

Fixes #545 
Using crane with nix versions prior to 2.5 (2.3 specifically in our case)

vendorMultipleCargoDeps: use backwards compatible groupBy (#545)

---

CHANGELOG.md
checks/default.nix
checks/nextest.nix
docs/API.md
lib/cargoNextest.nix

* This adds a convenience method of running `nextest` within `cargo llvm-cov` without having to wire up the internal details manually
Fixes #559

cargoNextest: support withLlvmCov

---

docs/faq/sandbox-unfriendly-build-scripts.md

I've updated postPatch script, so that it follows symlinks to nix store and does deep copy of all dependencies.
Also we need to completely remove references to nix store from our config.toml in case we use patches or git repositories

Update doc for unfriendly build scripts

---

CHANGELOG.md
pkgs/crane-utils/src/bin/crane-resolve-workspace-inheritance.rs

If workspace features dependency and workspace crate uses it, it is always gets merged as regular table (not inline one) so comments ends up in the following position:
```
[
dependencies.arbitrary ]
```
Take a look at the test for more info.
Fixes https://github.com/ipetkov/crane/issues/527

Fix bug with comment for inline table key

---

docs/SUMMARY.md
docs/overriding_derivations.md

Although package and derivation overrides are a `nixpkgs` concept, it is helpful to document a small primer for anyone unfamiliar with where the patterns come from.
Fixes #586

docs: add a primer on .override and .overrideAttrs

---

docs/API.md

The API docs seem wrong here, copy-pasta probably.

Fix typo in `cargoNextestExtraArgs` docs

---

CHANGELOG.md
docs/API.md
lib/cargoAudit.nix

It seems `cargo audit` does not inherit the rest of the cargo command line arguments, which means having `cargoExtraArgs` defined for it results in  errors like:  `error: unexpected argument '-F' found`.
The change removes the `cargoExtraArgs` from `cargoAudit.nix` to avoid mistakes.
Not sure how to best test it, feel free to point me in a direction and I'll implement something.
**cargo audit help**
```shell
» cargo audit --version
cargo-audit-audit 0.20.0
» cargo audit help
Audit Cargo.lock files for vulnerable crates
Usage: cargo audit [OPTIONS] [COMMAND]
Commands:
bin   scan compiled binaries
help  Print this message or the help of the given subcommand(s)
Options:
-c, --color <COLOR>              color configuration: always, never (default: auto)
-d, --db <DB> …
```

Remove cargoExtraArgs from cargoAudit

---

CHANGELOG.md
checks/cargoAudit.nix
checks/default.nix
checks/illegal-bin/Cargo.toml
checks/with-libs/Cargo.toml
checks/workspace-git/Cargo.toml
checks/workspace-hack/Cargo.toml
checks/workspace-inheritance/Cargo.toml
checks/workspace/Cargo.toml
docs/API.md
examples/end-to-end-testing/Cargo.toml
examples/end-to-end-testing/e2e_tests/Cargo.toml
examples/end-to-end-testing/flake.nix
examples/end-to-end-testing/server/Cargo.toml
examples/quick-start-workspace/Cargo.toml
examples/trunk-workspace/Cargo.toml
examples/trunk-workspace/client/Cargo.toml
examples/trunk-workspace/flake.nix
examples/trunk-workspace/server/Cargo.toml
examples/trunk-workspace/shared/Cargo.toml
lib/crateNameFromCargoToml.nix
lib/internalCrateNameFromCargoToml.nix

`crateNameFromCargoToml` now supports choosing a derivation name from `{package,workspace}.metadata.crane.name`. Choosing a name from `workspace.package.name` is now deprecated and will be removed in a future version
Fixes https://github.com/ipetkov/crane/issues/584

crateNameFromCargoToml: support selecting a name from `metadata`

---

checks/bindeps/Cargo.toml
checks/cleanCargoTomlTests/complex/Cargo.toml
checks/cleanCargoTomlTests/complex/expected.toml
checks/dependencyBuildScriptPerms/Cargo.toml
checks/illegal-bin/Cargo.toml
checks/mkDummySrcTests/workspace-bindeps/expected/Cargo.toml
checks/mkDummySrcTests/workspace-bindeps/input/Cargo.toml
checks/mkDummySrcTests/workspace-inheritance/expected/Cargo.toml
checks/mkDummySrcTests/workspace-inheritance/input/Cargo.toml
checks/mkDummySrcTests/workspace/expected/Cargo.toml
checks/mkDummySrcTests/workspace/input/Cargo.toml
checks/with-libs/Cargo.toml
checks/workspace-git/Cargo.toml
checks/workspace-hack/Cargo.toml
checks/workspace-inheritance/Cargo.toml
checks/workspace-not-at-root/workspace/Cargo.toml
checks/workspace-root/Cargo.toml
checks/workspace/Cargo.toml
examples/trunk-workspace/Cargo.toml

Cargo warns about workspaces not using `resolver = "2"` so we might as well be consistent everywhere

Use resolver = 2 in all Cargo.tomls

---

CHANGELOG.md
checks/cratePatching/0001-patch-test-repo.patch
checks/cratePatching/0002-patch-byteorder.patch
checks/cratePatching/default.nix
checks/default.nix
docs/API.md
docs/SUMMARY.md
docs/patching_dependency_sources.md
lib/downloadCargoPackage.nix
lib/downloadCargoPackageFromGit.nix
lib/vendorCargoDeps.nix
lib/vendorCargoRegistries.nix
lib/vendorGitDeps.nix
lib/vendorMultipleCargoDeps.nix

This change adds support to `vendorCargoDeps` (and friends) to allow overriding (i.e. patching) any arbitrary crate's sources, whether they are being vendored from a cargo registry or from a git repo
Fixes https://github.com/ipetkov/crane/issues/473

vendorCargoDeps: allow arbitrary overrides when vendoring sources

---

CHANGELOG.md
checks/trunk-outdated-bindgen/index.html
checks/trunk/index.html
examples/trunk-workspace/client/index.html
examples/trunk/index.html
lib/buildTrunkPackage.nix

Looks like the latest `trunk` version crashes if the network is inaccessible and version checks aren't disabled

buildTrunkPackage: disable version checks by default

---

CHANGELOG.md
docs/faq/custom-nixpkgs.md
docs/getting-started.md
docs/introduction/artifact-reuse.md
docs/introduction/sequential-builds.md
docs/local_development.md
examples/alt-registry/flake.nix
examples/quick-start-simple/flake.nix
examples/quick-start-workspace/flake.nix
examples/quick-start/flake.nix
examples/sqlx/flake.nix
extra-tests/alt-store/flake.nix
extra-tests/dummy-does-not-depend-on-flake-source-via-path/flake.nix
extra-tests/dummy-does-not-depend-on-flake-source-via-self/flake.nix
extra-tests/fetch-cargo-git/flake.nix
flake.nix

Most of our examples already indicate using `crane.mkLib` since that's the _generally correct_ thing to do regardless of whether `nixpkgs.legacyPackages` is what the caller wants or if they want to customize their `pkgs` instantiation (with overlays, or a cross build system, or both).
Not to mention that `crane.lib.${system}` is a bit of a footgun if you forget to set `crane.inputs.nixpkgs.follows = "nixpkgs"`. Although we have automation in place to keep the flake.lock updated, it's still possible to land in a confusing situation unless you are intimately familiar with how all your flake's inputs are wrangled...
I think long term it makes the most sense/least confusion to stick with a bring-your-own-nixpkgs workflow

flake: deprecate crane.lib.${system}

---

CHANGELOG.md
lib/setupHooks/removeReferencesToVendoredSources.nix
lib/setupHooks/removeReferencesToVendoredSourcesHook.sh

There is no reason to repeatedly crawl the vendor directories for each installed file, we can easily cache the results once up front.
Fixes https://github.com/ipetkov/crane/issues/620

removeReferencesToVendoredSources: cache vendorDir crawling

---

CHANGELOG.md
lib/setupHooks/removeReferencesToVendoredSources.nix

Fixes a bug introduced with #625.
`signIfRequired` is a shell function, not an executable, so we can't call it with `xargs`.
https://github.com/NixOS/nixpkgs/blob/7187b3ee8e2687106e8982b02d2890689471579e/pkgs/os-specific/darwin/signing-utils/utils.sh#L38-L43
```
xargs: signIfRequired: No such file or directory
```
Uses this approach:
https://github.com/NixOS/nixpkgs/blob/7187b3ee8e2687106e8982b02d2890689471579e/pkgs/os-specific/darwin/signing-utils/auto-sign-hook.sh#L19-L21
Tested locally with my build.

Fix `xargs signIfRequired`

---

default.nix
examples/cross-rust-overlay/flake.nix
flake.nix
lib/default.nix
lib/downloadCargoPackageFromGit.nix

Use a spliced scope that better allows for (more correctly) controlling what tools are used where when cross compiling.
Fixes https://github.com/ipetkov/crane/issues/628
Possibly related to https://github.com/ipetkov/crane/issues/551, though I still could not resolve that one yet

lib: use makeScopeWithSplicing' instead of makeScope

---

.github/workflows/test.yml
CHANGELOG.md
lib/default.nix
test/flake.lock
test/flake.nix

24.05 was recently released, 23.11 is deprecated and upstream support will be dropped soon

Drop support for nixpkgs-23.11

---

CHANGELOG.md
examples/cross-rust-overlay/flake.nix

* Sometimes we also need to set the TARGET_CC environment variable to allow cross compiling crates which also need to build a program to run on the build platform itself

Update cross compile example

---

.github/workflows/test.yml

Recent Nix releases keep being unstable or outright broken. Switch to using 2.18.2 (current version in nixos-unstable)

ci: stick to nix 2.18.2

---

CHANGELOG.md
checks/default.nix
checks/trunk.nix
default.nix
docs/API.md
docs/faq/custom-nixpkgs.md
docs/faq/invalid-metadata-files-for-crate.md
docs/overriding_derivations.md
examples/build-std/flake.nix
examples/cross-musl/flake.nix
examples/cross-rust-overlay/flake.nix
examples/custom-toolchain/flake.nix
examples/end-to-end-testing/flake.nix
examples/trunk-workspace/flake.nix
examples/trunk/flake.nix
lib/default.nix
lib/downloadCargoPackageFromGit.nix

`overrideToolchain` can now accept a function used to splice the rust toolchain:
```nix
craneLib = (crane.mkLib pkgs).overrideToolchain (p: p.rust-bin.stable.latest.default);
```
~~I don't fully understand why the toolchain needs be offset from `pkgsBuildHost` even when spliced. But this has always been the case.~~
Fixes https://github.com/ipetkov/crane/issues/648
Fixes https://github.com/ipetkov/crane/issues/551

Splice overrideToolchain

---

examples/build-std/flake.nix
examples/cross-musl/flake.nix
examples/cross-rust-overlay/flake.nix
examples/custom-toolchain/flake.nix
examples/end-to-end-testing/flake.nix
examples/trunk-workspace/flake.nix
examples/trunk/flake.nix
test/flake.nix

`oxalica/rust-overlay` removed their (public) input on `flake-utils` so we no longer need to override it
Refs https://github.com/ipetkov/crane/issues/662

Drop non-existent input override for oxalica/rust-overlay

---

flake.nix

I'd like to use the workspace template as documented on https://crane.dev/examples/quick-start-workspace.html . Running the provided command fails with `error: flake 'github:ipetkov/crane' does not provide attribute 'templates.quick-start-workspace' or 'quick-start-workspace'`, I think because the example is missing from the flake.

Add build-std and quick-start-workspace as flake templates

---

CHANGELOG.md
lib/vendorCargoRegistries.nix

This allows building packages with crates from custom registries that reference other custom registries.
It works by scanning packages from `Cargo.lock` and adding any missing registries to crane's generated `.cargo/config.toml`. This matches Cargo's behavior where the top level project doesn't necessarily have to explicitly define all transitive registries.
Fixes #456

Fix deeply nested registries

---

CHANGELOG.md
docs/API.md
lib/cargoNextest.nix

To resolve [issue (#675)](https://github.com/ipetkov/crane/issues/675) with the `cargoExtraArgs` attribute in `craneLib.cargoNextest` being placed in between `cargo <HERE> nextest` or `cargo <HERE> llvm-cov nextest` where there should be no options/flags.
Cargo flags cannot be used in this context. Only `cargo nextest run/archive` flags, which contain all the flags from `cargo test` (at least) are possible.
Sources I have checked:
* [cargo llvm-cov nextest](https://github.com/taiki-e/cargo-llvm-cov/blob/f349cb8b99c874a152a7605489b539764624867a/docs/cargo-llvm-cov-nextest.txt)
* [cargo nextest run](https://github.com/nextest-rs/nextest/blob/e70b4e645a0df7922e396e2bfe30f3e85abe1106/site/help-text/run-help.txt)
* [cargo nextest archive](https://github.com/nextest-rs/nextest/blob/e70b4e645a0df …

Cannot set cargoExtraArgs in craneLib.cargoNextest (#675)

---

CHANGELOG.md
docs/API.md
lib/buildPackage.nix
lib/setupHooks/installFromCargoBuildLog.nix
lib/setupHooks/installFromCargoBuildLogHook.sh

Doing so ends up resulting in PKG_CONFIG_PATH changing which may result in various `*-sys` crates needing to be rebuilt
Fixes #684

buildPackage: do not add `jq` to nativeBuildInputs

---

CHANGELOG.md
lib/downloadCargoPackageFromGit.nix

Related to https://github.com/ipetkov/crane/issues/689

downloadCargoPackageFromGit: set fetchLFS when an output hash is defined

---

CHANGELOG.md
docs/API.md
lib/downloadCargoPackageFromGit.nix
lib/vendorGitDeps.nix

Match the idioms established by nixpkgs, namely preferring using `hash` (which is more future compatible) than using `sha256` explicitly

downloadCargoPackageFromGit: take `hash` instead of `sha256`

---

CHANGELOG.md
docs/API.md
examples/quick-start-workspace/.config/hakari.toml
examples/quick-start-workspace/Cargo.toml
examples/quick-start-workspace/deny.toml
examples/quick-start-workspace/flake.nix
examples/quick-start-workspace/taplo.toml
examples/quick-start/deny.toml
examples/quick-start/flake.nix
examples/quick-start/taplo.toml
flake.nix
lib/default.nix
lib/taploFmt.nix

Closes #673 
Hello, this change adds a function to `mkLib` for checking formatting of TOML files. TOML files are extremely common, especially among Rust projects, and I find that in all of my use cases of `crane` between projects I am always manually adding checks for the formatting of `Cargo.toml` files, and other files such as `deny.toml`, `rust-toolchain.toml`, `rustfmt.toml` and so on.
I have a working copy of this on a local project, otherwise I wasn't sure how to add tests for it. I'm also sure that the copy-pasted code I took from `cargoFmt.nix` may include some things that don't belong, or may otherwise be going about it the wrong way. Regardless, this is what worked for me, please do instruct me on how to get this to a mergable state, I would greatly appreciate it!

Add `taploFmt` TOML format function to `mkLib`

---

docs/API.md

registryFromSparse: add missing API docs

---

CHANGELOG.md
docs/API.md
docs/SUMMARY.md
docs/faq/control-when-hooks-run.md
lib/buildDepsOnly.nix

We've gotten a lot of questions/confusion around how to separate hooks which need to run or not during `buildDepsOnly`. Typically this involves passing different arguments to `buildDepsOnly` vs something like `buildPackage`, but this change is meant to help make that a bit easier by setting `CRANE_BUILD_DEPS_ONLY` during `buildDepsOnly` builds so hooks can short circuit as appropriate if desired.
Related to https://github.com/ipetkov/crane/discussions/717

buildDepsOnly: set CRANE_BUILD_DEPS_ONLY env var when running

---

CHANGELOG.md
lib/setupHooks/removeReferencesToVendoredSourcesHook.sh

Debug builds might have a ton of references to sources, and `sed` does not like it when we feed it a massive amount of duplicates
Fixes https://github.com/ipetkov/crane/issues/744

removeReferencesToVendoredSourcesHook: dedup references

---

.github/workflows/test.yml
CHANGELOG.md
lib/default.nix
test/flake.lock
test/flake.nix

There's a new nixpkgs-stable release (24.11), so switch to testing with that

nixpkgs: drop support for 24.05

---

checks/mkDummySrcTests/multibin/expected/Cargo.toml
checks/mkDummySrcTests/multibin/expected/src/main.rs
checks/mkDummySrcTests/multibin/input/Cargo.toml
lib/mkDummySrc.nix

Fixes https://github.com/ipetkov/crane/issues/757

mkDummySrc: also consider main.rs when deduping bins

---

checks/mkDummySrcTests/custom-dummyrs/expected/benches/bench1.rs
checks/mkDummySrcTests/custom-dummyrs/expected/benches/custom.rs
checks/mkDummySrcTests/custom-dummyrs/expected/examples/custom.rs
checks/mkDummySrcTests/custom-dummyrs/expected/examples/example1.rs
checks/mkDummySrcTests/custom-dummyrs/expected/src/bin/bin1.rs
checks/mkDummySrcTests/custom-dummyrs/expected/src/bin/custom.rs
checks/mkDummySrcTests/custom-dummyrs/expected/src/lib.rs
checks/mkDummySrcTests/custom-dummyrs/expected/tests/custom.rs
checks/mkDummySrcTests/custom-dummyrs/expected/tests/test1.rs
checks/mkDummySrcTests/default.nix

Fixes https://github.com/ipetkov/crane/issues/767

Drop start feature/attribute as its going away

---

CHANGELOG.md
checks/nextest.nix
docs/API.md
examples/quick-start-workspace/flake.nix
examples/quick-start/flake.nix
lib/cargoNextest.nix

Newer versions of `cargo nextest` will error out if a partition does not have any tests, so it can be useful to pass `--no-tests=pass` (for example) to those runs.

cargoNextest: support passing extra args to each partition run

---

CHANGELOG.md
docs/API.md
lib/default.nix

This just adds `self` as `craneLib` to the crane lib attrset.
Motivation here is to allow to `callPackage` other file and access the crane lib instance in there.

Add craneLib as self-reference to lib

---

CHANGELOG.md
pkgs/crane-utils/default.nix

https://github.com/NixOS/nixpkgs/blob/master/doc/release-notes/rl-2505.section.md
`rustPlatform.fetchCargoTarball` has been deprecated - replace with `useFetchCargoVendor`
Mainly tested this on some private repos which were failing after upgrading to latest version of rust (and throwing a deprecation warning).

crane-utils/buildRustPackage - useFetchCargoVendor

---

CHANGELOG.md
lib/buildTrunkPackage.nix

`buildTrunkPackage` will attempt to read `installPhaseCommand` from the args, however we were stripping out `installPhaseCommand` from the args before we try to read it. This PR simply no longer strips `installPhaseCommand` from the args.
I also removed the filter for `installPhase` since it doesn't seem like there is really any need for it (even though users probably have no need to override `installPhase` if they can control `installPhaseCommand`)

fix: Don't ignore installPhaseCommand in trunkBuildPackage

---

examples/end-to-end-testing/flake.nix

The devshell is broken for `end-to-end-testing`. This changes `buildInputs` from pascal to camel case.

fix: `buildInputs` camel case

---

docs/overriding_derivations.md
examples/quick-start-workspace/flake.nix
examples/quick-start/flake.nix
test.sh

The quick-start and quick-start-workspace examples used fenix because it allows using cargo-llvm-cov, but its come up a few times that people are having trouble with certain configs and since I don't use it myself I can't always sort out what the issue is. For now we'll drop it from these examples just to cut down on confusion
Refs https://github.com/ipetkov/crane/discussions/829

examples: drop fenix from quick-start and quick-start-workspace

---

docs/SUMMARY.md
docs/faq/missing-files-during-checks.md
docs/source-filtering.md

Closes #835 
Adds a section to `source-filtering.md` which explains how to handle extra file sources which may be needed by flake checks.

doc: Add fileset filtering in flake checks section to FAQ/troubleshooting

---

lib/cargoNextest.nix

This was fixed with 0.9.72, the latest NixOS stable branch has 0.9.95

cargoNextest: drop Darwin workaround

---

CHANGELOG.md
docs/API.md
lib/mkDummySrc.nix

This allows for overriding the build script with a different value than the dummy lib.rs/main.rs files
Sometimes its useful to be able to use a real (or _more_ real) build script during `buildDepsOnly`. See https://github.com/ipetkov/crane/discussions/906

mkDummySrc: also accept dummyBuildScript
