ipetkov/crane

- CHANGELOG.md
- checks/default.nix
- checks/nextest.nix
- checks/simple/src/main.rs
- docs/API.md
- examples/quick-start/flake.nix
- lib/cargoNextest.nix
- lib/default.nix
Adds support for running tests via [cargo nextest](https://nexte.st/)
> Add cargo-nextest support

- README.md
Add FAQ about avoiding unnecessary rebuilds
Related to #73
> README: add FAQ about avoiding unnecessary rebuilds

- checks/cargoAudit.nix
- checks/simple-with-audit-toml/.cargo/audit.toml
fix tests, config file goes in .cargo/audit.toml
Fixes #98
> cargoAudit: fix tests, config file goes in .cargo/audit.toml

- docs/API.md
Fix some documentation typos
Originally reported in #86
> docs: fix typos

- checks/default.nix
- examples/alt-registry/flake.nix
- flake.lock
> Update flake deps

- README.md
Update with advice on patching Cargo.lock
Fixes #124
> readme: update with advice on patching Cargo.lock

- CHANGELOG.md
- checks/default.nix
- docs/API.md
- lib/cargoTest.nix
- lib/default.nix
Add `cargoTest` for just running the tests in a workspace
Fixes #108
> Add cargoTest for running crate tests

- docs/API.md
Fixup doc typos which were missed in #131
> Fixup docs

- .github/workflows/test.yml
- checks/cargoAudit.nix
- checks/compilesFresh.nix
- checks/default.nix
- checks/mkDummySrcTests/default.nix
- checks/nextest.nix
- examples/cross-musl/flake.nix
- examples/cross-rust-overlay/flake.nix
- extra-tests/dummy-does-not-depend-on-flake-source-via-path/flake.nix
- extra-tests/dummy-does-not-depend-on-flake-source-via-self/flake.nix
- flake.nix
- lib/cargoDoc.nix
- lib/cargoNextest.nix
- lib/cargoTarpaulin.nix
- lib/default.nix
- lib/downloadCargoPackage.nix
- lib/downloadCargoPackageFromGit.nix
- lib/findCargoFiles.nix
- lib/mkCargoDerivation.nix
- lib/mkDummySrc.nix
- lib/registryFromGitIndex.nix
- lib/vendorGitDeps.nix
Eliminate dead code and add a workflow for continuous checks
> Eliminate dead code

- CHANGELOG.md
- extra-tests/fetch-cargo-git/flake.nix
- extra-tests/fetch-cargo-git/test.sh
- extra-tests/test.sh
- lib/downloadCargoPackageFromGit.nix
The Cargo git repo contains numerous "case-0.1.0" Cargo.toml files in the testsuite (ex: [1](https://github.com/rust-lang/cargo/blob/5ccea519d43d09c0edf4b5dffc32e068fbf46296/tests/testsuite/init/simple_git/out/Cargo.toml) [2](https://github.com/rust-lang/cargo/blob/5ccea519d43d09c0edf4b5dffc32e068fbf46296/tests/testsuite/init/simple_bin/out/Cargo.toml) [3](https://github.com/rust-lang/cargo/blob/5ccea519d43d09c0edf4b5dffc32e068fbf46296/tests/testsuite/init/simple_hg/out/Cargo.toml)). This causes permission denials when we try to overwrite the previous ones:
```nix
let
crane = builtins.getFlake "git+https://github.com/ipetkov/crane?rev=b70e77d2e2d480a3a0bce3ecd2d981679588b23f";
drv = crane.lib.x86_64-linux.downloadCargoPackageFromGit {
git = "git+https://github.com/rust-lang/cargo";
rev = …
```
> downloadCargoPackageFromGit: Ignore crates with duplicate package IDs

- examples/quick-start/flake.nix
Fixes #156
Adds support for the default template to run on macos unmodified.
With this we see the following (note NixOS/Linux derivations should be unchanged, at least I couldn't find any difference in the derivations in any linked shared libraries on 22.05):
```
$ otool -L $(find -L result -type f)
result/bin/quick-start:                                                                                                                     
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)                                                
/nix/store/6kd227vx2kbj0hbndr7bnqymzfmc7711-Libsystem-1238.60.2/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 
1.0.0) …
```
> Update default template to work on macos

- docs/API.md
Made the example more copy-pastable :)
> Fixes `filterCargoSources` example in documentation

- CHANGELOG.md
- docs/API.md
- examples/alt-registry/flake.nix
- lib/downloadCargoPackage.nix
- lib/registryFromDownloadUrl.nix
- lib/registryFromGitIndex.nix
- lib/urlForCargoPackage.nix
Same as #162 but with my own updates pushed to it
Closes #159
> Allow passing arbitrary fetchurl args per registry

- docs/API.md
> cleanCargoSource: fix documentation typo

- README.md
> README: add FAQ about building workspace subsets

- docs/faq/sandbox-unfriendly-build-scripts.md
Fix example for sandbox unfriendly dependency workaround
Refs #200
> docs: fix example for sandbox unfriendly dependency workaround

- checks/default.nix
- docs/faq/workspace-not-at-source-root.md
Make example code for nested workspaces more universal
Refs #209
> docs: make example code for nested workspaces more universal

- checks/dependencyBuildScriptPerms/Cargo.lock
- checks/features/features/Cargo.lock
- checks/git-overlapping/Cargo.lock
- checks/git-repo-with-many-crates/Cargo.lock
- checks/grpcio-test/Cargo.lock
- checks/highs-sys-test/Cargo.lock
- checks/no_std/Cargo.lock
- checks/simple-git/Cargo.lock
- examples/alt-registry/Cargo.lock
- examples/cross-rust-overlay/Cargo.lock
> chore: bump all Cargo.locks

- docs/API.md
Hoping to clarify any potential confusion around this as reported in #223
> Update docs to clarify buildPackage installation behavior

- docs/API.md
- examples/quick-start-simple/flake.nix
- examples/quick-start/flake.nix
Clarify docs and add example of setting custom environment variable
Fixes #232
> docs: Clarify docs and add example of setting custom environment variable

- docs/SUMMARY.md
- docs/custom_cargo_commands.md
- docs/customizing_builds.md
- docs/local_development.md
- examples/quick-start-simple/flake.nix
- examples/quick-start/flake.nix
* add a section on customizing builds
* add an example for building custom command helpers
* add example on adding custom devShell env vars
* add local development section
Fixes https://github.com/ipetkov/crane/issues/169
Fixes https://github.com/ipetkov/crane/issues/235
Fixes https://github.com/ipetkov/crane/issues/250
Fixes https://github.com/ipetkov/crane/issues/251
> docs: add various new sections and examples

- examples/alt-registry/.gitignore
- examples/cross-musl/.gitignore
- examples/cross-rust-overlay/.gitignore
- examples/cross-windows/.gitignore
- examples/custom-toolchain/.gitignore
- examples/quick-start-simple/.gitignore
- examples/quick-start/.gitignore
Add .gitignore file to all examples so anyone starting with a template doesn't have to add their own
> templates: add .gitignore file

- examples/alt-registry/flake.nix
- examples/custom-toolchain/flake.nix
- examples/quick-start-simple/flake.nix
- examples/quick-start/flake.nix
Fixes https://github.com/ipetkov/crane/issues/253
> examples: correctly propagate devShell inputs from checks

- docs/SUMMARY.md
- docs/faq/rebuilds-with-different-toolchains.md
Refs https://github.com/ipetkov/crane/issues/249
> docs: add section about using different toolchains

- CHANGELOG.md
- pkgs/crane-utils/src/bin/crane-resolve-workspace-inheritance.rs
> fix: target workspace dependency resolution

- CHANGELOG.md
- checks/default.nix
- docs/API.md
- examples/quick-start/flake.nix
- flake.lock
- flake.nix
- lib/cargoLlvmCov.nix
- lib/default.nix
- lib/setupHooks/cargoHelperFunctionsHook.sh
> feat: add cargoLlvmCov

- CHANGELOG.md
- docs/API.md
- docs/custom_cargo_commands.md
- docs/customizing_builds.md
- docs/faq/patching-cargo-lock.md
- docs/faq/workspace-not-at-source-root.md
- docs/getting-started.md
- docs/introduction/artifact-reuse.md
- docs/introduction/sequential-builds.md
- docs/local_development.md
- docs/source-filtering.md
- examples/alt-registry/flake.nix
- examples/cross-musl/flake.nix
- examples/cross-rust-overlay/flake.nix
- examples/cross-windows/flake.nix
- examples/custom-toolchain/flake.nix
- examples/quick-start-simple/flake.nix
- examples/quick-start/flake.nix
- lib/crateNameFromCargoToml.nix
- lib/default.nix
- lib/internalCrateNameFromCargoToml.nix
- lib/path.nix
- pkgs/crane-utils/default.nix
- pkgs/default.nix
- shell.nix
> Add `path` as a convenience wrapper around `builtins.path`

- examples/quick-start/flake.nix
Fixes https://github.com/ipetkov/crane/issues/276
> quick-start: remove bogus follows clause

- CHANGELOG.md
- checks/default.nix
- lib/vendorCargoDeps.nix
Fixes https://github.com/ipetkov/crane/issues/275
> vendorCargoDeps: skip checking for cargoConfigs if src not set

- lib/crateNameFromCargoToml.nix
* The warning now shows a more in-depth explanation on how to silence it
Fixes https://github.com/ipetkov/crane/issues/281
> crateNameFromCargoToml: make warnings more useful

- docs/SUMMARY.md
- docs/advanced/advanced.md
- docs/advanced/overriding-function-behavior.md
> docs: document using `overrideScope'`

- docs/faq/constant-rebuilds.md
> Advise on using `nix derivation show -r` to debug rebuilds

- docs/source-filtering.md
Typo in docs.  I tested by using this code locally.
> docs: typo lib.filterCargoSources -> craneLib.filterCargoSources

- .github/workflows/test.yml
- CHANGELOG.md
- examples/build-std/flake.nix
Dropping support for nixos-22.11
> Update support to nixos-23.05

- checks/default.nix
- checks/grpcio-test/Cargo.lock
- checks/grpcio-test/Cargo.toml
- lib/cargoNextest.nix
Fixes https://github.com/ipetkov/crane/issues/347
> Fix tests to run on darwin

- docs/SUMMARY.md
- docs/faq/constant-rebuilds.md
- docs/faq/invalid-metadata-files-for-crate.md
Refs https://github.com/ipetkov/crane/issues/353
Refs https://github.com/ipetkov/crane/issues/351
> docs: update FAQs around rebuilds and other errors

- checks/dependencyBuildScriptPerms/Cargo.lock
- checks/features/features/Cargo.lock
- checks/git-overlapping/Cargo.lock
- checks/git-repo-with-many-crates/Cargo.lock
- checks/gitRevNoRef/Cargo.lock
- checks/grpcio-test/Cargo.lock
- checks/highs-sys-test/Cargo.lock
- checks/no_std/Cargo.lock
- checks/simple-git/Cargo.lock
- checks/trunk.nix
- checks/trunk/Cargo.lock
- examples/alt-registry/Cargo.lock
- examples/cross-rust-overlay/Cargo.lock
- examples/cross-rust-overlay/flake.nix
- examples/trunk-workspace/Cargo.lock
- examples/trunk-workspace/flake.nix
- examples/trunk/Cargo.lock
- examples/trunk/flake.nix
- flake.lock
- pkgs/crane-utils/Cargo.lock
> update all Cargo.locks

- CHANGELOG.md
- checks/simple-git-workspace-inheritance/Cargo.lock
- lib/downloadCargoPackageFromGit.nix
Fixes https://github.com/ipetkov/crane/issues/365
> downloadCargoPackageFromGit: resolve symlinks in crate directory

- .github/workflows/flakehub-publish-tagged.yml
> Add flakehub integration

- CHANGELOG.md
- checks/default.nix
- docs/API.md
- docs/local_development.md
- examples/alt-registry/flake.nix
- examples/build-std/flake.nix
- examples/custom-toolchain/flake.nix
- examples/quick-start-simple/flake.nix
- examples/quick-start/flake.nix
- examples/trunk-workspace/flake.nix
- examples/trunk/flake.nix
- lib/default.nix
- lib/devShell.nix
> Rust shell

- docs/SUMMARY.md
- docs/faq/rebuilds-with-proc-macros.md
Document a workaround for https://github.com/ipetkov/crane/issues/370
> Add FAQ about proc-macro rebuilds in `dev` mode

- docs/customizing_builds.md
The link to the manual specifies that it should be postInstall, not postInstallPhase
> Fix postInstall name

- checks/dependencyBuildScriptPerms/Cargo.lock
- checks/features/features/Cargo.lock
- checks/git-overlapping/Cargo.lock
- checks/git-repo-with-many-crates/Cargo.lock
- checks/gitRevNoRef/Cargo.lock
- checks/grpcio-test/Cargo.lock
- checks/highs-sys-test/Cargo.lock
- checks/no_std/Cargo.lock
- checks/overlapping-targets/Cargo.lock
- checks/simple-git-workspace-inheritance/Cargo.lock
- checks/simple-git/Cargo.lock
- checks/simple-with-audit-toml/Cargo.lock
- checks/simple/Cargo.lock
- checks/trunk/Cargo.lock
- checks/with-build-script-custom/Cargo.lock
- checks/with-build-script/Cargo.lock
- examples/cross-rust-overlay/Cargo.lock
- examples/end-to-end-testing/Cargo.lock
- examples/trunk-workspace/Cargo.lock
- examples/trunk/Cargo.lock
- extra-tests/dummy-does-not-depend-on-flake-source-via-path/Cargo.lock
- extra-tests/dummy-does-not-depend-on-flake-source-via-self/Cargo.lock
- pkgs/crane-utils/Cargo.lock
> chore: update all test deps

- checks/default.nix
> chore: fix test outputHashes

- lib/crateNameFromCargoToml.nix
Fixes https://github.com/ipetkov/crane/issues/359
> crateNameFromCargoToml: add hint for finding the source of the warning

- CHANGELOG.md
- pkgs/crane-utils/default.nix
* This should hopefully result in fewer surprises if someone is using a really ancient toolchain for their code since we'll use whatever is in nixpkgs to build craneUtils instead
> craneUtils: build with rustPlatform

- CHANGELOG.md
- docs/API.md
- lib/devShell.nix
Fixes https://github.com/ipetkov/crane/issues/383
> devShell: add clippy and rustfmt from the current toolchain

- checks/cargoDeny.nix
- checks/default.nix
- checks/trunk.nix
- docs/API.md
- examples/cross-windows/flake.nix
- examples/end-to-end-testing/flake.nix
- examples/trunk-workspace/flake.nix
- examples/trunk/flake.nix
- lib/cargoDeny.nix
> chore: clean up some dead code warnings

- CHANGELOG.md
- checks/default.nix
- docs/API.md
- lib/setupHooks/installCargoArtifactsHook.sh
Fixes https://github.com/ipetkov/crane/issues/81
> installCargoArtifactsHook: allow specifying additional zstd args

- examples/sqlx/flake.nix
As suggested in https://github.com/ipetkov/crane/pull/467#issuecomment-1832392928
> examples: simplify sqlx template

- .github/workflows/test.yml
- CHANGELOG.md
- ci/check-example.sh
- ci/ref-from-lock.sh
- test/flake.lock
- test/flake.nix
> chore: drop compatibility for nixpkgs-23.05

- .github/workflows/test.yml
- examples/quick-start/flake.nix
- examples/sqlx/flake.nix
Turns out we were accidentally ignoring errors when building the examples. This mitigates that oversight and fixes some Darwin build issues
> fix(ci): don't ignore errors from examples

- docs/API.md
- docs/SUMMARY.md
- docs/faq/rebuilds-pyo3.md
Fixes https://github.com/ipetkov/crane/issues/414
> docs: add note about avoiding pyo3 rebuilds

- lib/downloadCargoPackageFromGit.nix
- pkgs/crane-utils/Cargo.lock
- pkgs/crane-utils/Cargo.toml
- pkgs/crane-utils/default.nix
> crane-utils: bump dependencies

- CHANGELOG.md
- pkgs/crane-utils/Cargo.lock
- pkgs/crane-utils/Cargo.toml
- pkgs/crane-utils/default.nix
- pkgs/crane-utils/src/bin/crane-resolve-workspace-inheritance.rs
Noticed this edge case when investigating #527
> crane-utils: fix workspace dependency merge when it is not a table

- docs/examples/end-to-end-testing.md
> typo(end-to-end-testing.md)

- extra-tests/alt-store/test.sh
https://github.com/NixOS/nix/issues/10267
> tests: disable alt-store test on Nix 2.21.0

- CHANGELOG.md
- docs/API.md
- lib/default.nix
- lib/urlForCargoPackage.nix
https://blog.rust-lang.org/2024/03/11/crates-io-download-changes.html
> crateRegistries: use crates.io's CDN to download sources

- CHANGELOG.md
- checks/default.nix
- lib/setupHooks/inheritCargoArtifactsHook.sh
- lib/setupHooks/installCargoArtifactsHook.sh
Fixes https://github.com/ipetkov/crane/issues/538
> inheritCargoArtifactsHook: correctly handle nested CARGO_TARGET_DIR

- docs/examples/alt-registry.md
- docs/examples/build-std.md
- docs/examples/cross-musl.md
- docs/examples/cross-rust-overlay.md
- docs/examples/cross-windows.md
- docs/examples/custom-toolchain.md
- docs/examples/end-to-end-testing.md
- docs/examples/quick-start-simple.md
- docs/examples/quick-start.md
- docs/examples/sqlx.md
- docs/examples/trunk-workspace.md
- docs/examples/trunk.md
- extra-tests/alt-store/test.sh
Fixes https://github.com/ipetkov/crane/issues/568
> docs: reword quickstart examples for existing projects

- CHANGELOG.md
- lib/default.nix
Fixes https://github.com/ipetkov/crane/issues/570
> Add a warning if an unsupported version of nixpkgs is used

- pkgs/crane-utils/Cargo.lock
- pkgs/crane-utils/default.nix
- pkgs/crane-utils/src/bin/crane-resolve-workspace-inheritance.rs
> chore: bump crane-utils deps

- CHANGELOG.md
- checks/simple-git/Cargo.lock
- checks/simple-git/Cargo.toml
- lib/vendorMultipleCargoDeps.nix
Fixes https://github.com/ipetkov/crane/issues/576
> vendorCargoDeps: handle unused patch dependencies

- examples/cross-windows/flake.nix
fixes https://github.com/ipetkov/crane/issues/572
> examples/cross-windows: fix issues related to openssl and libring

- checks/default.nix
- examples/end-to-end-testing/Cargo.lock
- examples/end-to-end-testing/flake.nix
- examples/end-to-end-testing/server/Cargo.toml
- examples/end-to-end-testing/server/src/main.rs
> chore: update end-to-end-example deps

- CHANGELOG.md
- docs/API.md
- lib/cargoDoc.nix
> fix(cargoDoc): Support cross-compilation of docs

- examples/quick-start-simple/flake.nix
Fixes https://github.com/ipetkov/crane/issues/592
> examples: tweak quick-start-simple to warn against accidental rebuilds

- examples/quick-start-simple/flake.nix
Follow up from https://github.com/ipetkov/crane/pull/605
Fixes https://github.com/ipetkov/crane/issues/592
> examples: fix quick-start-simple warning against accidental rebuilds

- CHANGELOG.md
- docs/API.md
- lib/downloadCargoPackage.nix
- lib/downloadCargoPackageFromGit.nix
Fixes https://github.com/ipetkov/crane/issues/618
> Fix crate vendoring to not run the default `fixup` phase

- CHANGELOG.md
- checks/cleanCargoTomlTests/complex-underscores/Cargo.toml
- checks/cleanCargoTomlTests/complex-underscores/expected.toml
- checks/cleanCargoTomlTests/default.nix
- lib/cleanCargoToml.nix
Fixes https://github.com/ipetkov/crane/issues/610
> cleanCargoToml: also clean variants using underscores

- examples/cross-rust-overlay/Cargo.lock
- examples/end-to-end-testing/Cargo.lock
- examples/sqlx/Cargo.lock
- examples/trunk-workspace/Cargo.lock
- examples/trunk-workspace/flake.nix
- examples/trunk/Cargo.lock
- examples/trunk/flake.nix
> chore: bump all example Cargo.locks

- examples/end-to-end-testing/Cargo.lock
- examples/end-to-end-testing/server/Cargo.toml
- examples/sqlx/Cargo.lock
- examples/sqlx/Cargo.toml
> chore: bump sqlx to 0.8 in examples

- docs/SUMMARY.md
- docs/faq/building-with-non-rust-includes.md
- docs/faq/git-dep-cannot-find-relative-path.md
> docs: add a FAQ entry about git-deps and relative file paths

- CHANGELOG.md
- docs/API.md
- lib/cargoDoc.nix
Fixes https://github.com/ipetkov/crane/issues/707
> cargoDoc: add a fallback search for non-cross-compiled docs

- docs/API.md
Came up in https://github.com/ipetkov/crane/discussions/703
> docs: document how to override mkShell/stdenv for devShell

- CHANGELOG.md
- lib/vendorCargoRegistries.nix
Fixes https://github.com/ipetkov/crane/issues/702
> vendorCargoRegistries: warn when registry names are not found

- CHANGELOG.md
- checks/default.nix
- docs/API.md
- lib/cargoDocTest.nix
- lib/default.nix
Closes #719
* Add `cargoDocTest`
* Add note that `cargoNextest` doesn't run doctests
* Fix erroneous reference to `cargoTestArgs` (instead of `cargoTestExtraArgs`) in documentation for `cargoTest`
> Add `cargoDocTest`

- docs/examples/alt-registry.md
Suggested in https://github.com/ipetkov/crane/issues/702#issuecomment-2398859082
> docs: add hint to stage .cargo/config.toml when using alt registries

- checks/default.nix
> checks: add regression test that cleanCargoSource works with non-paths

- CHANGELOG.md
- lib/buildTrunkPackage.nix
Fixes https://github.com/ipetkov/crane/issues/735
> buildTrunkPackage: set --release=true on newer trunk versions

- CHANGELOG.md
- lib/setupHooks/removeReferencesToVendoredSourcesHook.sh
Fixes https://github.com/ipetkov/crane/issues/734
> removeReferencesToVendoredSourcesHook: avoid using /dev/fd directly

- CHANGELOG.md
- checks/default.nix
- docs/API.md
- lib/buildDepsOnly.nix
Fixes https://github.com/ipetkov/crane/issues/748
> buildDepsOnly: prefer `dummySrc` when specified for fallback values

- CHANGELOG.md
- checks/default.nix
- lib/crateNameFromCargoToml.nix
Fixes https://github.com/ipetkov/crane/issues/761
> cargoTomlContents: ignore context of Cargo.toml file

- .github/workflows/test.yml
- test/flake.lock
- test/flake.nix
> ci: add a test input for deadnix

- examples/quick-start-workspace/.cargo/audit.toml
- examples/quick-start/.cargo/audit.toml
- test.sh
https://github.com/ipetkov/crane/issues/421#issuecomment-2581810441
> Examples: add cargo-audit config to disable checking for yanked crates from within the sandbox

- .github/workflows/test.yml
- flake.nix
- test.sh
- test/flake.nix
Fixes https://github.com/ipetkov/crane/issues/785
> checks: move all tests to the test flake

- CHANGELOG.md
- checks/default.nix
- lib/setupHooks/removeReferencesToRustToolchainHook.sh
- lib/setupHooks/removeReferencesToVendoredSourcesHook.sh
- test/flake.nix
Fixes https://github.com/ipetkov/crane/issues/808
> Handle files with spaces in `removeReferencesToRustToolchainHook` and `removeReferencesToVendoredSourcesHook`

- lib/mkCrossToolchainEnv.nix
> Fix eval with allowAliases = false

- examples/end-to-end-testing/.gitignore
- examples/trunk-workspace/.gitignore
- examples/trunk/.gitignore
> templates: add .gitignore for `end-to-end-testing`

- examples/cross-rust-overlay/Cargo.lock
- examples/end-to-end-testing/Cargo.lock
- examples/quick-start-workspace/Cargo.lock
- examples/sqlx/Cargo.lock
- examples/trunk-workspace/Cargo.lock
- examples/trunk-workspace/flake.nix
- examples/trunk/Cargo.lock
- examples/trunk/flake.nix
> examples: bump Cargo.locks

- docs/SUMMARY.md
- docs/faq/cross-compiling-aws-lc-sys.md
Addition of FAQ page as discussed in #870
Resolves #870
> Add faq page about aws-lc-sys cross compilation

- examples/quick-start-workspace/flake.nix
- examples/quick-start/flake.nix
Fixes https://github.com/ipetkov/crane/issues/876
> examples: deny all rustdoc warnings

- checks/default.nix
- checks/illegalReferences.nix
- examples/alt-registry/flake.nix
- examples/end-to-end-testing/flake.nix
- examples/sqlx/flake.nix
- test/flake.nix
> Avoid recently deprecated packages

- CHANGELOG.md
- checks/cleanCargoTomlTests/complex-underscores/Cargo.toml
- checks/cleanCargoTomlTests/complex-underscores/expected.toml
- checks/cleanCargoTomlTests/complex/Cargo.toml
- checks/cleanCargoTomlTests/complex/expected.toml
- lib/cleanCargoToml.nix
Fixes https://github.com/ipetkov/crane/issues/898
> cleanCargoToml: preserve targets' `harness` attribute

- docs/API.md
> docs: fix some typos

- checks/mkDummySrcTests/default.nix
> checks: drop compat handling for remarshal <0.16
